
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND CALL COMMENT DIVIDE DO EACH ELIF EQUALS EQUALSTO FALSE FLOAT FUNCTION IF IN INT MAKE MINUS MULTIPLY NAME NOT OR PLUS PRINT RETURN THEN TO TRUE UNTIL WHILE \n    calc : exp\n         | E \n     \n    exp : exp PLUS exp\n        | exp MINUS exp\n        | exp MULTIPLY exp\n        | exp DIVIDE exp\n    \n    exp : INT\n        | FLOAT\n     E : '
    
_lr_action_items = {'INT':([0,6,7,8,9,],[4,4,4,4,4,]),'FLOAT':([0,6,7,8,9,],[5,5,5,5,5,]),'$end':([0,1,2,3,4,5,10,11,12,13,],[-9,0,-1,-2,-7,-8,-3,-4,-5,-6,]),'PLUS':([2,4,5,10,11,12,13,],[6,-7,-8,6,6,6,6,]),'MINUS':([2,4,5,10,11,12,13,],[7,-7,-8,7,7,7,7,]),'MULTIPLY':([2,4,5,10,11,12,13,],[8,-7,-8,8,8,8,8,]),'DIVIDE':([2,4,5,10,11,12,13,],[9,-7,-8,9,9,9,9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'calc':([0,],[1,]),'exp':([0,6,7,8,9,],[2,10,11,12,13,]),'E':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> calc","S'",1,None,None,None),
  ('calc -> exp','calc',1,'p_calc','lexer.py',122),
  ('calc -> E','calc',1,'p_calc','lexer.py',123),
  ('exp -> exp PLUS exp','exp',3,'p_exp','lexer.py',132),
  ('exp -> exp MINUS exp','exp',3,'p_exp','lexer.py',133),
  ('exp -> exp MULTIPLY exp','exp',3,'p_exp','lexer.py',134),
  ('exp -> exp DIVIDE exp','exp',3,'p_exp','lexer.py',135),
  ('exp -> INT','exp',1,'p_exp_int_float','lexer.py',141),
  ('exp -> FLOAT','exp',1,'p_exp_int_float','lexer.py',142),
  ('E -> <empty>','E',0,'p_E','lexer.py',147),
]
